//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLy
    {
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string hoQL { get; set; }
        public string tenQL { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string anhQL { get; set; }
        public string sdtQL { get; set; }
        public string email { get; set; }
    }
}
